### ISSUE TITLE
Rollbar: Error while calling custom checkIgnore(), removing TypeError: args[1].indexOf is not a function

### ISSUE THREAD

**Issue by ericjoy94** [rollbar/rollbar.js#694]

**Comment by ericjoy94** [comment]
Rollbar is logging me this issue  since I updated my rollbar to 2.4.2 .

**Comment by jessewgibbs** [comment]
@ericjoy94 thanks for bringing thisissue to our attention.

@rokob any idea what might have changed between 2.0.4 and 2.4.2?

**Comment by rokob** [comment]
Nothing changed between 2.0.4 and 2.4.2 that would affect that inputs to the checkIgnore function. It looks like you are trying to ignore some uncaught exceptions, `args[1]` has been the Error object from as early as 2.0.0 (https://github.com/rollbar/rollbar.js/blob/v2.0.0/src/browser/rollbar.js#L103) so that checkIgnore function should never have worked. `args[0]` however which is the string message for the uncaught exception should work.

**Comment by rokob** [comment]
Did you update the entire snippet or just the rollbarJsUrl?
