### ISSUE TITLE
Typescript declaration file contains syntax errors.

### ISSUE THREAD

**Issue by saulogt** [rollbar/rollbar.js#348]
After updating the api version to 2.1.1 I got these errors:

```
13     constructor(options: Rollbar.Configuration?);
                                                 ~
node_modules/rollbar/index.d.ts(13,47): error TS1005: ',' expected.

18     public lastError(): Error?;
                                ~
node_modules/rollbar/index.d.ts(18,30): error TS1144: '{' or ';' expected.

43     export type Callback = (err: Error?, response: object) => void;
                                         ~
node_modules/rollbar/index.d.ts(43,39): error TS1005: ',' expected.

43     export type Callback = (err: Error?, response: object) => void;
                                          ~
node_modules/rollbar/index.d.ts(43,40): error TS1138: Parameter declaration expected.
``` 
Probably the idea was to make Error an optional value
